#version 450
#extension GL_NV_gpu_shader5 : enable
#extension GL_NV_shader_atomic_int64: require
#extension GL_ARB_compute_variable_group_size: enable

layout(std430, binding = 0) buffer depthBuffer {
    uint64_t _depth[]; //Los 32 bits más significativos son para la profundidad, los 32 restantes para el atributo del punto.
};

uniform float cameraFoV;
uniform float occlusionThreshold;
uniform uvec2 windowSize;

uint linearizePosition(ivec2 windowPosition)
{
    return windowPosition.y * windowSize.x + windowPosition.x;
}

float getOcclusionAngle(ivec2 pixelCoords, ivec2 imgSize, float depth)
{
	ivec2 begin = clamp(pixelCoords - 1, ivec2(0), ivec2(imgSize) - 1);
	ivec2 end = clamp(pixelCoords + 1, ivec2(0), ivec2(imgSize) - 1);
	float minAngle = 0xfffffff;

	for (int y = begin.y; y <= end.y; ++y) {
		for (int x = begin.x; x <= end.x; ++x) {
			if (x == pixelCoords.x && y == pixelCoords.y) 
				continue;

			uint tempDepthNeighbor = uint(_depth[linearizePosition(ivec2(x, y))] >> 32);
			if (tempDepthNeighbor == ~uint(0)) 
				continue;

			float depthNeighbour = uintBitsToFloat(uint(_depth[linearizePosition(ivec2(x, y))] >> 32));
			float widthPixel = 2.0f * max(depth, depthNeighbour) * tan(cameraFoV / float(imgSize.x));
			minAngle = min(abs(atan(widthPixel, depth - depthNeighbour)), minAngle);
		}
	}
	
	return minAngle;
}

layout(local_size_variable) in;
void main() {
    const uint pixelIndex = gl_GlobalInvocationID.x;
    const uint totalPixels = windowSize.x * windowSize.y;
	
    if (pixelIndex < totalPixels) {
        ivec2 pixelCoords;
        pixelCoords.y = int(floor(pixelIndex / windowSize.x));
        pixelCoords.x = int(pixelIndex % windowSize.x);
        uint codedColor = uint(_depth[pixelIndex]);
		
        if (codedColor != ~uint(0)) {
			uint uDepth = uint(_depth[pixelIndex] >> 32);
			float depth = uintBitsToFloat(uDepth);
			
			if (getOcclusionAngle(pixelCoords, ivec2(windowSize), depth) < occlusionThreshold) 
				_depth[pixelIndex] = _depth[pixelIndex] | uint64_t(~uint(0));
		}
    }
}
