#version 460
#extension GL_NV_gpu_shader5 : enable
#extension GL_NV_shader_atomic_int64: require
#extension GL_ARB_compute_variable_group_size: enable

layout(std430, binding = 0) restrict readonly buffer depthBuffer {
    uint _depth[];
};

layout(std430, binding = 7) restrict readonly buffer vPosition {
    float _points[];
};

layout(std430, binding = 9) restrict readonly buffer vAttributes {
    uint att[];
};

layout (std430, binding = 11) buffer color01Buffer	{ 
	uint64_t _colorBuffer01[]; 
};

layout (std430, binding = 12) buffer color02Buffer	{ 
	uint64_t _colorBuffer02[];
};

uniform float 	distanceThreshold;
uniform uint 	pointsOffset;
uniform uint 	numPoints;
uniform mat4 	mModelViewProj;
uniform uvec2 	windowSize;

uniform vec3 	firstGradientPoint;
uniform vec3 	secondGradientPoint;
uniform vec3 	lastGradientPoint;

subroutine vec3 GetColor(uint codedColor);
subroutine uniform GetColor GetColorUniform;

subroutine ( GetColor )
vec3 getColorUnpackingUint(uint codedColor) {
    return vec4(unpackUnorm4x8(codedColor)).xyz;
}

subroutine ( GetColor )
vec3 getColorFromFloat(uint codedColor) {
    float val = uintBitsToFloat(codedColor);
    vec3 color;
    if (val < 0.5f)
        color = mix(firstGradientPoint, secondGradientPoint, val*2f);
    else
        color = mix(secondGradientPoint, lastGradientPoint, (val - 0.5f)*2f);
    return color;
}

layout(local_size_variable) in;

void main() {
	uint index = gl_GlobalInvocationID.x;
	
    if (index < numPoints) {
        index += pointsOffset;
        uint baseIndex = index * 3;
        vec4 projectedPosition = mModelViewProj * vec4(_points[baseIndex], _points[baseIndex + 1], _points[baseIndex + 2], 1);
        projectedPosition.xyz /= projectedPosition.w;
		
        if (projectedPosition.w > 0.0 && projectedPosition.x > -1.0 && projectedPosition.x < 1.0 && projectedPosition.y > -1.0 && projectedPosition.y < 1.0) {
            ivec2 windowPosition 	= ivec2((projectedPosition.xy * 0.5f + 0.5f) * windowSize);
            uint pixelIndex 		= windowPosition.y * windowSize.x + windowPosition.x;
            const float minDepth 	= uintBitsToFloat(_depth[pixelIndex]);
			
			if (projectedPosition.w < minDepth * distanceThreshold)		
			{
			    uint codedColor = uint(att[index]);
				uvec3 color = uvec3(GetColorUniform(codedColor) * 255.0f);
				
				uint64_t rg = (uint64_t(color.r) << 32) | color.g;
				uint64_t ba = (uint64_t(color.b) << 32) | 1;

				atomicAdd(_colorBuffer01[pixelIndex], rg);
				atomicAdd(_colorBuffer02[pixelIndex], ba);
			}
		}
	}
}
