#version 450
#extension GL_NV_gpu_shader5 : enable
#extension GL_NV_shader_atomic_int64: require
#extension GL_ARB_compute_variable_group_size: enable

layout(std430, binding = 0) restrict readonly buffer depthBuffer {
    uint64_t _depth[]; //Los 32 bits más significativos son para la profundidad, los 32 restantes para el atributo del punto.
};

#define NULL ~uint(0)

uniform vec3 firstGradientPoint;
uniform vec3 secondGradientPoint;
uniform vec3 lastGradientPoint;
uniform float zNear, zFar;
uniform float edlStrength;
uniform int numNeighbors;

ivec2 edlNeighbourhood[4] = { ivec2(1, 0), ivec2(-1, 0), ivec2(0, 1), ivec2(0, -1) };

float linearize(float depth)
{
    return (depth - zNear) / (zFar - zNear);
}

uint linearizePosition(ivec2 windowPosition, ivec2 windowSize)
{
    return windowPosition.y * windowSize.x + windowPosition.x;
}

subroutine float GetShadingFactor(ivec2 position, ivec2 windowSize);
subroutine uniform GetShadingFactor GetShadingFactorUniform;

subroutine ( GetShadingFactor )
float getIdentityFactor(ivec2 position, ivec2 windowSize) {
    return 1.0f;
}

subroutine ( GetShadingFactor )
float getEDLFactor(ivec2 position, ivec2 windowSize) {
    float depth = log2(linearize(uintBitsToFloat(uint(_depth[linearizePosition(position, windowSize)] >> 32))));
    float sum = 0.0;

    for (int i = 0; i < 4; i++)
    {
		ivec2 samplePosition = clamp(position + edlNeighbourhood[i].xy, ivec2(0), windowSize - ivec2(1));
		uint unsignedNeighborDepth = uint(_depth[linearizePosition(samplePosition, windowSize)] >> 32);
		
		if (unsignedNeighborDepth != NULL)
		{
			float neighbourDepth = log2(linearize(uintBitsToFloat(unsignedNeighborDepth)));
			sum += max(0.0, depth - neighbourDepth);  
		}	
    }

    return exp(-sum / float(4) * edlStrength);
}

subroutine vec3 GetColor(uint codedColor);
subroutine uniform GetColor GetColorUniform;

subroutine ( GetColor )
vec3 getColorUnpackingUint(uint codedColor) {
    return vec4(unpackUnorm4x8(codedColor)).xyz;
}

subroutine ( GetColor )
vec3 getColorFromFloat(uint codedColor) {
    float val = uintBitsToFloat(codedColor);
    vec3 color;
    if (val < 0.5f)
        color = mix(firstGradientPoint, secondGradientPoint, val*2f);
    else
        color = mix(secondGradientPoint, lastGradientPoint, (val - 0.5f)*2f);
    return color;
}

bool fillBackground(ivec2 pixelCoords, ivec2 imgSize) {
	ivec2 minCoords = max(pixelCoords - ivec2(1), ivec2(0)), maxCoords = min(pixelCoords + ivec2(1), imgSize - ivec2(1));
	uint8_t 
		lt = uint8_t(uint(_depth[linearizePosition(ivec2(minCoords.x, maxCoords.y), imgSize)]) != NULL), 
		lm = uint8_t(uint(_depth[linearizePosition(ivec2(minCoords.x, pixelCoords.y), imgSize)]) != NULL), 
		lb = uint8_t(uint(_depth[linearizePosition(ivec2(minCoords.x, minCoords.y), imgSize)]) != NULL), 
		mt = uint8_t(uint(_depth[linearizePosition(ivec2(pixelCoords.x, maxCoords.y), imgSize)]) != NULL), 
		mb = uint8_t(uint(_depth[linearizePosition(ivec2(pixelCoords.x, minCoords.y), imgSize)]) != NULL), 
		rt = uint8_t(uint(_depth[linearizePosition(ivec2(maxCoords.x, maxCoords.y), imgSize)]) != NULL), 
		rm = uint8_t(uint(_depth[linearizePosition(ivec2(maxCoords.x, pixelCoords.y), imgSize)]) != NULL), 
		rb = uint8_t(uint(_depth[linearizePosition(ivec2(maxCoords.x, minCoords.y), imgSize)]) != NULL);
	
	uint8_t sum = lt + lm + lb + mt + mb + rt + rm + rb;
	uint8_t m0 = mt + rt + rm + rb + mb;
	uint8_t m1 = lt + mt + rt + lm + rm;
	uint8_t m2 = lt + mt + lm + lb + mb;
	uint8_t m3 = lm + rm + lb + mb + rb;
	uint8_t m4 = lt + mt + rt + rm + rb;
	uint8_t m5 = lt + mt + rt + lm + lb;
	uint8_t m6 = lt + lm + lb + mb + rb;
	uint8_t m7 = rt + rm + rb + mb + lb;
	
	return sum == uint8_t(8) || (m0 * m1 * m2 * m3 * m4 * m5 * m6 * m7) != uint8_t(0);
}

uniform layout(rgba8) restrict image2D colorOutput;

layout(local_size_variable) in;
void main() {
    const uint pixelIndex = gl_GlobalInvocationID.x;
    const ivec2 imgSize = imageSize(colorOutput);
    const uint totalPixels = imgSize.x * imgSize.y;
	
    if (pixelIndex < totalPixels) { //
        const uint py = uint(floor(pixelIndex / imgSize.x));
        const uint px = pixelIndex % imgSize.x;
        const ivec2 pixelCoords = ivec2(px, py);
        uint codedColor = uint(_depth[pixelIndex]);

		//
		if (uint(_depth[pixelIndex] >> 32) != NULL) {
			vec4 color = vec4(GetColorUniform(codedColor), 1);
			imageStore(colorOutput, pixelCoords, vec4(GetColorUniform(codedColor) * GetShadingFactorUniform(pixelCoords, imgSize), 1.0f));
		}
		else {
            vec4 finalColor = vec4(0, 0, 0, 0);
			
            for (int x = max(pixelCoords.x - numNeighbors, 0); x <= min(pixelCoords.x + numNeighbors, imgSize.x - 1); x++) {
                for (int y = max(pixelCoords.y - numNeighbors, 0); y <= min(pixelCoords.y + numNeighbors, imgSize.y - 1); y++) {
                    uint pixelId = y * imgSize.x + x;
                    codedColor = uint(_depth[pixelId]);
                    if (pixelId != pixelIndex && codedColor != NULL) {
                        finalColor.xyz += GetColorUniform(codedColor);
                        finalColor.a += 1;
                    }
                }
            }
            if (finalColor.a > 0) {
                finalColor /= finalColor.a;
				
				imageStore(colorOutput, pixelCoords, vec4(finalColor.rgb * GetShadingFactorUniform(pixelCoords, imgSize), 1.0f));
            }		
        }
    }
}
