#version 460
#extension GL_NV_gpu_shader5 : enable
#extension GL_NV_shader_atomic_int64: require
#extension GL_ARB_compute_variable_group_size: enable

layout(std430, binding = 0) restrict readonly buffer depthBuffer {
    uint _depth[]; 
};

layout (std430, binding = 12) buffer color02Buffer	{ 
	uint64_t _colorBuffer02[];
};

#define EPSILON 0.0000001f

uniform float cameraFoV;
uniform uvec2 windowSize;

uint linearizePosition(ivec2 windowPosition, ivec2 windowSize)
{
    return windowPosition.y * windowSize.x + windowPosition.x;
}

float getOcclusionAngle(ivec2 pixelCoords, ivec2 imgSize, float depth)
{
	ivec2 begin = clamp(pixelCoords - 1, ivec2(0), ivec2(imgSize) - 1);
	ivec2 end = clamp(pixelCoords + 1, ivec2(0), ivec2(imgSize) - 1);
	float minAngle = 3.402823466e+38;

	for (int y = begin.y; y <= end.y; ++y) {
		for (int x = begin.x; x <= end.x; ++x) {
			if (x == pixelCoords.x && y == pixelCoords.y) 
				continue;

			uint tempDepthNeighbor = _depth[linearizePosition(ivec2(x, y), imgSize)];
			if (tempDepthNeighbor == ~uint(0)) 
				continue;

			float depthNeighbour = uintBitsToFloat(_depth[linearizePosition(ivec2(x, y), imgSize)]);
			float widthPixel = 2.0f * max(depth, depthNeighbour) * tan(cameraFoV / float(imgSize.x));
			minAngle = min(abs(atan(widthPixel, depth - depthNeighbour)), minAngle);
		}
	}
	
	return minAngle;
}

layout(local_size_variable) in;

void main() {
	const uint pixelIndex = gl_GlobalInvocationID.x;
    const uint totalPixels = windowSize.x * windowSize.y;
	
    if (pixelIndex < totalPixels) {
        ivec2 pixelCoords;
        pixelCoords.y = int(floor(pixelIndex / windowSize.x));
        pixelCoords.x = int(pixelIndex % windowSize.x);
		
        if (uint(_colorBuffer02[pixelIndex]) > EPSILON) {
			float depth = uintBitsToFloat(_depth[pixelIndex]);
			if (getOcclusionAngle(pixelCoords, ivec2(windowSize), depth) < 0.1) {
				_colorBuffer02[pixelIndex] &= ~uint64_t(0xFFFFFFFF);		// Set to zero
			}
		}
    }
}
