#version 460

#extension GL_ARB_compute_variable_group_size: enable
#extension GL_ARB_gpu_shader_int64: require

layout (local_size_variable) in;

layout(std430, binding = 0) restrict buffer depthBuffer {
	uint _depth[]; 
};

layout (std430, binding = 11) buffer color01Buffer	{ 
	uint64_t _colorBuffer01[]; 
};

layout (std430, binding = 12) buffer color02Buffer	{ 
	uint64_t _colorBuffer02[];
};

uniform vec3 backgroundColor;
uniform uvec2 windowSize;
uniform layout(binding = 0, rgba8) writeonly image2D colorOutput;

void main()
{
	uint index = gl_GlobalInvocationID.x;
	if (index >= windowSize.x * windowSize.y) return;
	const ivec2 imgSize = imageSize(colorOutput);
	uvec2 pixelCoords;
    pixelCoords.y = uint(floor(index / imgSize.x));
    pixelCoords.x = index % imgSize.x;

	_depth[index] = 0;
	_depth[index] = ~_depth[index];
	_colorBuffer01[index] = _colorBuffer02[index] = 0;
    imageStore(colorOutput, ivec2(pixelCoords), vec4(backgroundColor,1));
}